events { worker_connections 1024; 
}

http {
    upstream backend_pool {
        server backend:8000;
    }

    upstream frontend_pool {
        # This is the critical line:
        server us_frontend_dev:3500; 
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_pool/;
        }

        location / {
            proxy_pass http://frontend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}